### ISSUE TITLE
Enhancement request: Checkpoint merger

### ISSUE THREAD

**Issue by svenkevs** [GuernikaCore/GuernikaModelConverter#1]
I understand that the format used by Apple has some limitations in using LoRas, and right now the best option is to first merge LoRas into a checkpoint and then convert the merged model to mlcore. So a feature for this model converter app to first merge a checkpoint with other checkpoints/LoRas, which is then directly converted would be nice.

It would make my workflow a bit easier. I could use a single app and run it all while I'm doing something else (due to swap file usage, it takes quite long to convert full SDXL checkpoints). I am sure other users are in this situation as well.

In any case, great work on the app! Until earlier today I was doing it with the CLI, this makes things a lot comfier.

**Comment by GuiyeC** [comment]
@svenkevs could you tell me what tool are you using to merge the LoRAs into a checkpoint?

**Comment by GuiyeC** [comment]
@svenkevs This should now be possible on the latest version
