### ISSUE TITLE
Compile guernikatools with nuitka

### ISSUE THREAD

**Issue by czkoko** [GuernikaCore/GuernikaModelConverter#3]
hello @GuiyeC :
The initialization of guernikatools packaged with pyinstaller is particularly slow, and you need to wait 1-2 minutes each time before the conversion can start.
I used nuitka to compile the guernikatools package into an executable program. After replacing the GuernikaTools file in GuernikaModelConverter, No need to wait, start converting immediately.
nuitka can convert py into C code for compilation, and it does not release a large number of packaged environments like pyinstaller during runtime, making it faster.
I used the following command to test successfully, but it only works in the local environment:
```shell
python3 -m nuitka --assume-yes-for-download --output-dir=./GuernikaModelConverter ./guernikatools/torch2coreml.py
```
Adding the `--standalone` parameter can compile the entire running environment to run on other computers, but some errors have been encountered. If you understand, you can research it.

**Comment by GuiyeC** [comment]
@czkoko thanks for the suggestion, I have given this a try and I'm not able to compile anything containing coremltools, for example:
```python
import coremltools as ct
```

Using nuitka with that simple file gives out this error:
```
FATAL: Error, failed to find path @rpath/libcoremlpython.dylib (resolved DLL to /Users/guiye/miniforge3/envs/guernika/lib/python3.10/site-packages/coremltools/libcoremlpython.dylib) for /Users/guiye/miniforge3/envs/guernika/lib/python3.10/site-packages/coremltools/libcoremlpython.so from 'coremltools', please report the bug.
```

It takes a loooong time to test this, so I will leave this for a later date, I'll give this another try or file an issue on their repo but for now I'll stick with pyinstaller, if you are ever successful at compiling a --standalone --onefile with nuitka I'll gladly follow your instructions.
