### ISSUE TITLE
Unable to convert SDXL

### ISSUE THREAD

**Issue by czkoko** [GuernikaCore/GuernikaModelConverter#4]
Diffusers have updated the API, and now it is impossible to convert the SDXL model in the safetensors format.

And whether it is SD1.5 or SDXL, the safetensors format must have a yaml file of the same name next to it, otherwise an error will occur.

[https://github.com/huggingface/diffusers/issues/4837](https://github.com/huggingface/diffusers/issues/4837)

**Comment by GuiyeC** [comment]
@czkoko thanks for the report, I think the latest version 7.0.1 should fix this, if you confirm I'll close this issue.

**Comment by czkoko** [comment]
Yes, 7.0.1 has solved the problem, thank you.

In addition, I also found a small UI related problem. The Diffusers and checkpoint selection buttons do not respond after clicking. The file selection box will appear after switching to other tabs. Maybe it is a MacOS14 bug? This problem has not occurred before.
